using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEditor;

public class ExampleResourcesManagementEditor
{
    [InitializeOnLoadMethod]
    static void InitializeOnLoadMethod()
    {
        KSwordKit.Contents.ResourcesManagement.ResourcesManager.AutoGeneratedResourcePathFilePath = "Assets/KSwordKit/Examples/ExampleResourcesManagement/AutoGenerated/AutoGeneratedResourcePath.cs";

    }
}
