
/*************************************************************************
 *  Copyright (C), 2020-2021. All rights reserved.
 *
 *  FileName: BuildConst.cs
 *  Author: ks   
 *  Version: 1.0.0   
 *  CreateDate: 2020-7-6
 *  File Description: 
 *      该文件由 KSwordKit 生成，每次生成资源包就会重新生成该文件，请勿修改里面的内容。
 *      该文件用于快速查找资源对象的引用路径，编写代码时方便快捷。
 *************************************************************************/

namespace KSwordKit.Contents.ResourcesManagement.AutoGenerated.AutoGeneratedResourcePath
{
    
	/// <summary>
	/// 此处的真实资源路径为: Assets
	/// <para>使用 API：<see cref="Assets.Path"/> 获取该路径的字符串</para>
	/// </summary>
	public class Assets
	{
	    /// <summary>
	    /// 真实资源路径：Assets
	    /// </summary>
	    public const string Path = "Assets";
	    
		/// <summary>
		/// 此处的真实资源路径为: Assets/KSwordKit
		/// <para>使用 API：<see cref="KSwordKit.Path"/> 获取该路径的字符串</para>
		/// </summary>
		public class KSwordKit
		{
		    /// <summary>
		    /// 真实资源路径：Assets/KSwordKit
		    /// </summary>
		    public const string Path = "Assets/KSwordKit";
		    
			/// <summary>
			/// 此处的真实资源路径为: Assets/KSwordKit/Examples
			/// <para>使用 API：<see cref="Examples.Path"/> 获取该路径的字符串</para>
			/// </summary>
			public class Examples
			{
			    /// <summary>
			    /// 真实资源路径：Assets/KSwordKit/Examples
			    /// </summary>
			    public const string Path = "Assets/KSwordKit/Examples";
			    
				/// <summary>
				/// 此处的真实资源路径为: Assets/KSwordKit/Examples/ExampleResourcesManagement
				/// <para>使用 API：<see cref="ExampleResourcesManagement.Path"/> 获取该路径的字符串</para>
				/// </summary>
				public class ExampleResourcesManagement
				{
				    /// <summary>
				    /// 真实资源路径：Assets/KSwordKit/Examples/ExampleResourcesManagement
				    /// </summary>
				    public const string Path = "Assets/KSwordKit/Examples/ExampleResourcesManagement";
				    
					/// <summary>
					/// 此处的真实资源路径为: Assets/KSwordKit/Examples/ExampleResourcesManagement/Test2.unity
					/// <para>使用 API：<see cref="Test2_unity.Path"/> 获取该路径的字符串</para>
					/// </summary>
					public class Test2_unity
					{
					    /// <summary>
					    /// 真实资源路径：Assets/KSwordKit/Examples/ExampleResourcesManagement/Test2.unity
					    /// </summary>
					    public const string Path = "Assets/KSwordKit/Examples/ExampleResourcesManagement/Test2.unity";
					    
					}

					/// <summary>
					/// 此处的真实资源路径为: Assets/KSwordKit/Examples/ExampleResourcesManagement/Test3.unity
					/// <para>使用 API：<see cref="Test3_unity.Path"/> 获取该路径的字符串</para>
					/// </summary>
					public class Test3_unity
					{
					    /// <summary>
					    /// 真实资源路径：Assets/KSwordKit/Examples/ExampleResourcesManagement/Test3.unity
					    /// </summary>
					    public const string Path = "Assets/KSwordKit/Examples/ExampleResourcesManagement/Test3.unity";
					    
					}

					/// <summary>
					/// 此处的真实资源路径为: Assets/KSwordKit/Examples/ExampleResourcesManagement/Test.unity
					/// <para>使用 API：<see cref="Test_unity.Path"/> 获取该路径的字符串</para>
					/// </summary>
					public class Test_unity
					{
					    /// <summary>
					    /// 真实资源路径：Assets/KSwordKit/Examples/ExampleResourcesManagement/Test.unity
					    /// </summary>
					    public const string Path = "Assets/KSwordKit/Examples/ExampleResourcesManagement/Test.unity";
					    
					}

					/// <summary>
					/// 此处的真实资源路径为: Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources
					/// <para>使用 API：<see cref="Resources.Path"/> 获取该路径的字符串</para>
					/// </summary>
					public class Resources
					{
					    /// <summary>
					    /// 真实资源路径：Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources
					    /// </summary>
					    public const string Path = "Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources";
					    
						/// <summary>
						/// 此处的真实资源路径为: Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/prefabs
						/// <para>使用 API：<see cref="prefabs.Path"/> 获取该路径的字符串</para>
						/// </summary>
						public class prefabs
						{
						    /// <summary>
						    /// 真实资源路径：Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/prefabs
						    /// </summary>
						    public const string Path = "Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/prefabs";
						    
							/// <summary>
							/// 此处的真实资源路径为: Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/prefabs/loadSceneButton.prefab
							/// <para>使用 API：<see cref="loadSceneButton_prefab.Path"/> 获取该路径的字符串</para>
							/// </summary>
							public class loadSceneButton_prefab
							{
							    /// <summary>
							    /// 真实资源路径：Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/prefabs/loadSceneButton.prefab
							    /// </summary>
							    public const string Path = "Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/prefabs/loadSceneButton.prefab";
							    
							}

						}

						/// <summary>
						/// 此处的真实资源路径为: Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/texture
						/// <para>使用 API：<see cref="texture.Path"/> 获取该路径的字符串</para>
						/// </summary>
						public class texture
						{
						    /// <summary>
						    /// 真实资源路径：Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/texture
						    /// </summary>
						    public const string Path = "Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/texture";
						    
							/// <summary>
							/// 此处的真实资源路径为: Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/texture/背景
							/// <para>使用 API：<see cref="背景.Path"/> 获取该路径的字符串</para>
							/// </summary>
							public class 背景
							{
							    /// <summary>
							    /// 真实资源路径：Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/texture/背景
							    /// </summary>
							    public const string Path = "Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/texture/背景";
							    
								/// <summary>
								/// 此处的真实资源路径为: Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/texture/背景/扩张背景.png
								/// <para>使用 API：<see cref="扩张背景_png.Path"/> 获取该路径的字符串</para>
								/// </summary>
								public class 扩张背景_png
								{
								    /// <summary>
								    /// 真实资源路径：Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/texture/背景/扩张背景.png
								    /// </summary>
								    public const string Path = "Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/texture/背景/扩张背景.png";
								    
								}

								/// <summary>
								/// 此处的真实资源路径为: Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/texture/背景/背景光效.png
								/// <para>使用 API：<see cref="背景光效_png.Path"/> 获取该路径的字符串</para>
								/// </summary>
								public class 背景光效_png
								{
								    /// <summary>
								    /// 真实资源路径：Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/texture/背景/背景光效.png
								    /// </summary>
								    public const string Path = "Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/texture/背景/背景光效.png";
								    
								}

								/// <summary>
								/// 此处的真实资源路径为: Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/texture/背景/海天背景.png
								/// <para>使用 API：<see cref="海天背景_png.Path"/> 获取该路径的字符串</para>
								/// </summary>
								public class 海天背景_png
								{
								    /// <summary>
								    /// 真实资源路径：Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/texture/背景/海天背景.png
								    /// </summary>
								    public const string Path = "Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/texture/背景/海天背景.png";
								    
								}

							}

							/// <summary>
							/// 此处的真实资源路径为: Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/texture/进度条
							/// <para>使用 API：<see cref="进度条.Path"/> 获取该路径的字符串</para>
							/// </summary>
							public class 进度条
							{
							    /// <summary>
							    /// 真实资源路径：Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/texture/进度条
							    /// </summary>
							    public const string Path = "Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/texture/进度条";
							    
								/// <summary>
								/// 此处的真实资源路径为: Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/texture/进度条/lod-1.png
								/// <para>使用 API：<see cref="lod中划线1_png.Path"/> 获取该路径的字符串</para>
								/// </summary>
								public class lod中划线1_png
								{
								    /// <summary>
								    /// 真实资源路径：Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/texture/进度条/lod-1.png
								    /// </summary>
								    public const string Path = "Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/texture/进度条/lod-1.png";
								    
								}

								/// <summary>
								/// 此处的真实资源路径为: Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/texture/进度条/lod-2.png
								/// <para>使用 API：<see cref="lod中划线2_png.Path"/> 获取该路径的字符串</para>
								/// </summary>
								public class lod中划线2_png
								{
								    /// <summary>
								    /// 真实资源路径：Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/texture/进度条/lod-2.png
								    /// </summary>
								    public const string Path = "Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/texture/进度条/lod-2.png";
								    
								}

							}

							/// <summary>
							/// 此处的真实资源路径为: Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/texture/个人信息
							/// <para>使用 API：<see cref="个人信息.Path"/> 获取该路径的字符串</para>
							/// </summary>
							public class 个人信息
							{
							    /// <summary>
							    /// 真实资源路径：Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/texture/个人信息
							    /// </summary>
							    public const string Path = "Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/texture/个人信息";
							    
								/// <summary>
								/// 此处的真实资源路径为: Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/texture/个人信息/个人信息修改名字.png
								/// <para>使用 API：<see cref="个人信息修改名字_png.Path"/> 获取该路径的字符串</para>
								/// </summary>
								public class 个人信息修改名字_png
								{
								    /// <summary>
								    /// 真实资源路径：Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/texture/个人信息/个人信息修改名字.png
								    /// </summary>
								    public const string Path = "Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/texture/个人信息/个人信息修改名字.png";
								    
								}

								/// <summary>
								/// 此处的真实资源路径为: Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/texture/个人信息/改名.png
								/// <para>使用 API：<see cref="改名_png.Path"/> 获取该路径的字符串</para>
								/// </summary>
								public class 改名_png
								{
								    /// <summary>
								    /// 真实资源路径：Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/texture/个人信息/改名.png
								    /// </summary>
								    public const string Path = "Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/texture/个人信息/改名.png";
								    
								}

								/// <summary>
								/// 此处的真实资源路径为: Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/texture/个人信息/个人信息背景.png
								/// <para>使用 API：<see cref="个人信息背景_png.Path"/> 获取该路径的字符串</para>
								/// </summary>
								public class 个人信息背景_png
								{
								    /// <summary>
								    /// 真实资源路径：Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/texture/个人信息/个人信息背景.png
								    /// </summary>
								    public const string Path = "Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/texture/个人信息/个人信息背景.png";
								    
								}

								/// <summary>
								/// 此处的真实资源路径为: Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/texture/个人信息/个人信息图标.png
								/// <para>使用 API：<see cref="个人信息图标_png.Path"/> 获取该路径的字符串</para>
								/// </summary>
								public class 个人信息图标_png
								{
								    /// <summary>
								    /// 真实资源路径：Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/texture/个人信息/个人信息图标.png
								    /// </summary>
								    public const string Path = "Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/texture/个人信息/个人信息图标.png";
								    
								}

							}

							/// <summary>
							/// 此处的真实资源路径为: Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/texture/按钮
							/// <para>使用 API：<see cref="按钮.Path"/> 获取该路径的字符串</para>
							/// </summary>
							public class 按钮
							{
							    /// <summary>
							    /// 真实资源路径：Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/texture/按钮
							    /// </summary>
							    public const string Path = "Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/texture/按钮";
							    
								/// <summary>
								/// 此处的真实资源路径为: Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/texture/按钮/随机事件名字.png
								/// <para>使用 API：<see cref="随机事件名字_png.Path"/> 获取该路径的字符串</para>
								/// </summary>
								public class 随机事件名字_png
								{
								    /// <summary>
								    /// 真实资源路径：Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/texture/按钮/随机事件名字.png
								    /// </summary>
								    public const string Path = "Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/texture/按钮/随机事件名字.png";
								    
								}

								/// <summary>
								/// 此处的真实资源路径为: Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/texture/按钮/打卡任务按钮.png
								/// <para>使用 API：<see cref="打卡任务按钮_png.Path"/> 获取该路径的字符串</para>
								/// </summary>
								public class 打卡任务按钮_png
								{
								    /// <summary>
								    /// 真实资源路径：Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/texture/按钮/打卡任务按钮.png
								    /// </summary>
								    public const string Path = "Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/texture/按钮/打卡任务按钮.png";
								    
								}

								/// <summary>
								/// 此处的真实资源路径为: Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/texture/按钮/视屏.png
								/// <para>使用 API：<see cref="视屏_png.Path"/> 获取该路径的字符串</para>
								/// </summary>
								public class 视屏_png
								{
								    /// <summary>
								    /// 真实资源路径：Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/texture/按钮/视屏.png
								    /// </summary>
								    public const string Path = "Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/texture/按钮/视屏.png";
								    
								}

								/// <summary>
								/// 此处的真实资源路径为: Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/texture/按钮/按钮.png
								/// <para>使用 API：<see cref="按钮_png.Path"/> 获取该路径的字符串</para>
								/// </summary>
								public class 按钮_png
								{
								    /// <summary>
								    /// 真实资源路径：Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/texture/按钮/按钮.png
								    /// </summary>
								    public const string Path = "Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/texture/按钮/按钮.png";
								    
								}

								/// <summary>
								/// 此处的真实资源路径为: Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/texture/按钮/4字广告.png
								/// <para>使用 API：<see cref="_4字广告_png.Path"/> 获取该路径的字符串</para>
								/// </summary>
								public class _4字广告_png
								{
								    /// <summary>
								    /// 真实资源路径：Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/texture/按钮/4字广告.png
								    /// </summary>
								    public const string Path = "Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/texture/按钮/4字广告.png";
								    
								}

								/// <summary>
								/// 此处的真实资源路径为: Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/texture/按钮/项目升级按钮动画.png
								/// <para>使用 API：<see cref="项目升级按钮动画_png.Path"/> 获取该路径的字符串</para>
								/// </summary>
								public class 项目升级按钮动画_png
								{
								    /// <summary>
								    /// 真实资源路径：Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/texture/按钮/项目升级按钮动画.png
								    /// </summary>
								    public const string Path = "Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/texture/按钮/项目升级按钮动画.png";
								    
								}

								/// <summary>
								/// 此处的真实资源路径为: Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/texture/按钮/图标
								/// <para>使用 API：<see cref="图标.Path"/> 获取该路径的字符串</para>
								/// </summary>
								public class 图标
								{
								    /// <summary>
								    /// 真实资源路径：Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/texture/按钮/图标
								    /// </summary>
								    public const string Path = "Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/texture/按钮/图标";
								    
									/// <summary>
									/// 此处的真实资源路径为: Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/texture/按钮/图标/7.png
									/// <para>使用 API：<see cref="_7_png.Path"/> 获取该路径的字符串</para>
									/// </summary>
									public class _7_png
									{
									    /// <summary>
									    /// 真实资源路径：Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/texture/按钮/图标/7.png
									    /// </summary>
									    public const string Path = "Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/texture/按钮/图标/7.png";
									    
									}

									/// <summary>
									/// 此处的真实资源路径为: Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/texture/按钮/图标/8.png
									/// <para>使用 API：<see cref="_8_png.Path"/> 获取该路径的字符串</para>
									/// </summary>
									public class _8_png
									{
									    /// <summary>
									    /// 真实资源路径：Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/texture/按钮/图标/8.png
									    /// </summary>
									    public const string Path = "Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/texture/按钮/图标/8.png";
									    
									}

									/// <summary>
									/// 此处的真实资源路径为: Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/texture/按钮/图标/6.png
									/// <para>使用 API：<see cref="_6_png.Path"/> 获取该路径的字符串</para>
									/// </summary>
									public class _6_png
									{
									    /// <summary>
									    /// 真实资源路径：Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/texture/按钮/图标/6.png
									    /// </summary>
									    public const string Path = "Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/texture/按钮/图标/6.png";
									    
									}

									/// <summary>
									/// 此处的真实资源路径为: Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/texture/按钮/图标/4.png
									/// <para>使用 API：<see cref="_4_png.Path"/> 获取该路径的字符串</para>
									/// </summary>
									public class _4_png
									{
									    /// <summary>
									    /// 真实资源路径：Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/texture/按钮/图标/4.png
									    /// </summary>
									    public const string Path = "Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/texture/按钮/图标/4.png";
									    
									}

									/// <summary>
									/// 此处的真实资源路径为: Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/texture/按钮/图标/fudai.png
									/// <para>使用 API：<see cref="fudai_png.Path"/> 获取该路径的字符串</para>
									/// </summary>
									public class fudai_png
									{
									    /// <summary>
									    /// 真实资源路径：Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/texture/按钮/图标/fudai.png
									    /// </summary>
									    public const string Path = "Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/texture/按钮/图标/fudai.png";
									    
									}

									/// <summary>
									/// 此处的真实资源路径为: Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/texture/按钮/图标/5.png
									/// <para>使用 API：<see cref="_5_png.Path"/> 获取该路径的字符串</para>
									/// </summary>
									public class _5_png
									{
									    /// <summary>
									    /// 真实资源路径：Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/texture/按钮/图标/5.png
									    /// </summary>
									    public const string Path = "Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/texture/按钮/图标/5.png";
									    
									}

									/// <summary>
									/// 此处的真实资源路径为: Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/texture/按钮/图标/3.png
									/// <para>使用 API：<see cref="_3_png.Path"/> 获取该路径的字符串</para>
									/// </summary>
									public class _3_png
									{
									    /// <summary>
									    /// 真实资源路径：Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/texture/按钮/图标/3.png
									    /// </summary>
									    public const string Path = "Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/texture/按钮/图标/3.png";
									    
									}

									/// <summary>
									/// 此处的真实资源路径为: Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/texture/按钮/图标/2.png
									/// <para>使用 API：<see cref="_2_png.Path"/> 获取该路径的字符串</para>
									/// </summary>
									public class _2_png
									{
									    /// <summary>
									    /// 真实资源路径：Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/texture/按钮/图标/2.png
									    /// </summary>
									    public const string Path = "Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/texture/按钮/图标/2.png";
									    
									}

									/// <summary>
									/// 此处的真实资源路径为: Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/texture/按钮/图标/1.png
									/// <para>使用 API：<see cref="_1_png.Path"/> 获取该路径的字符串</para>
									/// </summary>
									public class _1_png
									{
									    /// <summary>
									    /// 真实资源路径：Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/texture/按钮/图标/1.png
									    /// </summary>
									    public const string Path = "Assets/KSwordKit/Examples/ExampleResourcesManagement/Resources/texture/按钮/图标/1.png";
									    
									}

								}

							}

						}

					}

				}

			}

		}

	}

}
